name: sde_framework
channels:
  - conda-forge
dependencies:
  - ipykernel
  - pandas=2.2.3
  - python=3.11.12
  - scikit-learn=1.6.1
  - sdv=1.22.1
  - pip:
      - be-great==0.0.9
      - realtabformer==0.2.2
      - table-evaluator==1.7.2.post1